require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LevenhoodsController do

  # This should return the minimal set of attributes required to create a valid
  # Levenhood. As you add validations to Levenhood, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LevenhoodsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all levenhoods as @levenhoods" do
      levenhood = Levenhood.create! valid_attributes
      get :index, {}, valid_session
      assigns(:levenhoods).should eq([levenhood])
    end
  end

  describe "GET show" do
    it "assigns the requested levenhood as @levenhood" do
      levenhood = Levenhood.create! valid_attributes
      get :show, {:id => levenhood.to_param}, valid_session
      assigns(:levenhood).should eq(levenhood)
    end
  end

  describe "GET new" do
    it "assigns a new levenhood as @levenhood" do
      get :new, {}, valid_session
      assigns(:levenhood).should be_a_new(Levenhood)
    end
  end

  describe "GET edit" do
    it "assigns the requested levenhood as @levenhood" do
      levenhood = Levenhood.create! valid_attributes
      get :edit, {:id => levenhood.to_param}, valid_session
      assigns(:levenhood).should eq(levenhood)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Levenhood" do
        expect {
          post :create, {:levenhood => valid_attributes}, valid_session
        }.to change(Levenhood, :count).by(1)
      end

      it "assigns a newly created levenhood as @levenhood" do
        post :create, {:levenhood => valid_attributes}, valid_session
        assigns(:levenhood).should be_a(Levenhood)
        assigns(:levenhood).should be_persisted
      end

      it "redirects to the created levenhood" do
        post :create, {:levenhood => valid_attributes}, valid_session
        response.should redirect_to(Levenhood.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved levenhood as @levenhood" do
        # Trigger the behavior that occurs when invalid params are submitted
        Levenhood.any_instance.stub(:save).and_return(false)
        post :create, {:levenhood => {}}, valid_session
        assigns(:levenhood).should be_a_new(Levenhood)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Levenhood.any_instance.stub(:save).and_return(false)
        post :create, {:levenhood => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested levenhood" do
        levenhood = Levenhood.create! valid_attributes
        # Assuming there are no other levenhoods in the database, this
        # specifies that the Levenhood created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Levenhood.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => levenhood.to_param, :levenhood => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested levenhood as @levenhood" do
        levenhood = Levenhood.create! valid_attributes
        put :update, {:id => levenhood.to_param, :levenhood => valid_attributes}, valid_session
        assigns(:levenhood).should eq(levenhood)
      end

      it "redirects to the levenhood" do
        levenhood = Levenhood.create! valid_attributes
        put :update, {:id => levenhood.to_param, :levenhood => valid_attributes}, valid_session
        response.should redirect_to(levenhood)
      end
    end

    describe "with invalid params" do
      it "assigns the levenhood as @levenhood" do
        levenhood = Levenhood.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Levenhood.any_instance.stub(:save).and_return(false)
        put :update, {:id => levenhood.to_param, :levenhood => {}}, valid_session
        assigns(:levenhood).should eq(levenhood)
      end

      it "re-renders the 'edit' template" do
        levenhood = Levenhood.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Levenhood.any_instance.stub(:save).and_return(false)
        put :update, {:id => levenhood.to_param, :levenhood => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested levenhood" do
      levenhood = Levenhood.create! valid_attributes
      expect {
        delete :destroy, {:id => levenhood.to_param}, valid_session
      }.to change(Levenhood, :count).by(-1)
    end

    it "redirects to the levenhoods list" do
      levenhood = Levenhood.create! valid_attributes
      delete :destroy, {:id => levenhood.to_param}, valid_session
      response.should redirect_to(levenhoods_url)
    end
  end

end
